name: Build and Upload Package to Snowflake

on:
  workflow_dispatch: {}

jobs:
  build-and-upload-package:
    name: Build package and upload to Snowflake stage
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: trip_pipeline
      ZIP_DIR: package
      ZIP_FILE_NAME: trip_pipeline.zip
      STAGE_NAME: OPS.PROC.PROC_STAGE
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_DATABASE: OPS
      SNOWFLAKE_SCHEMA: PROC
      PRIVATE_KEY_BASE64: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_BASE64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build ZIP for Snowflake Stored Procedure
        run: |
          mkdir -p $ZIP_DIR/$PACKAGE_NAME
          rsync -av --exclude="__pycache__" src/$PACKAGE_NAME/ $ZIP_DIR/$PACKAGE_NAME/
          mkdir -p $ZIP_DIR/python
          pip install -r requirements.txt --target $ZIP_DIR/python
          cp requirements.txt $ZIP_DIR/

          cd $ZIP_DIR
          zip -r $ZIP_FILE_NAME .
          echo "Created ZIP package:"
          ls -lh $ZIP_FILE_NAME

      - name: Set up Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          cli-version: "3.11.0"

      - name: Decode private key and configure Snowflake connection
        run: |
          echo "$PRIVATE_KEY_BASE64" | base64 --decode > snowflake_key.pem
          chmod 600 snowflake_key.pem
          
          snow connection add \
            --connection-name github_ci_connection \
            --accountname "$SNOWFLAKE_ACCOUNT" \
            --username "$SNOWFLAKE_USER" \
            --private-key-file snowflake_key.pem \
            --role "$SNOWFLAKE_ROLE" \
            --database "$SNOWFLAKE_DATABASE" \
            --schema "$SNOWFLAKE_SCHEMA" \
            --authenticator SNOWFLAKE_JWT \
            --no-interactive \
            --default


      - name: Upload ZIP to Snowflake stage
        run: |
          ZIP_PATH="$ZIP_DIR/$ZIP_FILE_NAME"
          echo "Uploading $ZIP_PATH to @$STAGE_NAME ..."
          snow stage copy "$ZIP_PATH" "@$STAGE_NAME" --overwrite